use crate::traits::{Clipboard, ClipboardSnapshot};
use magpie_core::Content;
use objc2_app_kit::NSPasteboard;

const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

pub struct MacClipboard {
    inner: arboard::Clipboard,
}

impl MacClipboard {
    pub fn new() -> Result<Self, String> {
        Ok(MacClipboard {
            inner: arboard::Clipboard::new().map_err(|e| e.to_string())?,
        })
    }

    fn change_count() -> i64 {
        let pb = NSPasteboard::generalPasteboard();
        pb.changeCount() as i64
    }

    fn is_concealed() -> bool {
        let pb = NSPasteboard::generalPasteboard();
        let Some(types) = pb.types() else { return false };
        types.iter().any(|t| {
            let s = t.to_string();
            CONCEALED_TYPES.iter().any(|c| *c == s)
        })
    }
}

impl Clipboard for MacClipboard {
    fn snapshot(&mut self) -> ClipboardSnapshot {
        let change_token = Self::change_count() as u64;
        let concealed = Self::is_concealed();
        let content = if let Ok(text) = self.inner.get_text() {
            if text.is_empty() { None } else { Some(Content::Text(text)) }
        } else if let Ok(img) = self.inner.get_image() {
            Some(Content::Image { bytes: tagged_rgba(&img) })
        } else {
            None
        };
        ClipboardSnapshot { content, change_token, concealed }
    }

    fn set_text(&mut self, text: &str) -> Result<(), String> {
        self.inner.set_text(text.to_string()).map_err(|e| e.to_string())
    }

    fn set_content(&mut self, content: &Content) -> Result<(), String> {
        match content {
            Content::Text(t) => self.inner.set_text(t.clone()).map_err(|e| e.to_string()),
            Content::Rich { text, .. } => self.inner.set_text(text.clone()).map_err(|e| e.to_string()),
            Content::Files(paths) => self.inner.set_text(paths.join("\n")).map_err(|e| e.to_string()),
            Content::Image { .. } => Err("image set not supported in v1".into()),
        }
    }
}

/// Stable, dimension-tagged raw-RGBA blob so identical images hash equal.
/// (Real PNG re-encoding + thumbnailing happens in the app's image cache.)
fn tagged_rgba(img: &arboard::ImageData) -> Vec<u8> {
    let mut out = Vec::with_capacity(8 + img.bytes.len());
    out.extend_from_slice(&(img.width as u32).to_le_bytes());
    out.extend_from_slice(&(img.height as u32).to_le_bytes());
    out.extend_from_slice(&img.bytes);
    out
}
