use crate::traits::{Clipboard, ClipboardSnapshot};
use magpie_core::Content;
use objc2_app_kit::NSPasteboard;
use objc2_foundation::NSString;

const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// Convert a `public.file-url` value (`file:///percent%20encoded`) to a plain
/// filesystem path. Returns `None` for non-`file:` URLs. Finder emits
/// `file:///path`, so after the scheme the remainder is the (percent-encoded) path.
fn file_url_to_path(url: &str) -> Option<String> {
    let rest = url.strip_prefix("file://")?;
    // Strip a trailing slash Finder appends to directory URLs, but keep root "/".
    let trimmed = if rest.len() > 1 {
        rest.trim_end_matches('/')
    } else {
        rest
    };
    let decoded = percent_decode(trimmed);
    if decoded.is_empty() {
        None
    } else {
        Some(decoded)
    }
}

/// Minimal percent-decoding (`%20` → space, etc.). No external dependency.
fn percent_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let Ok(b) = u8::from_str_radix(&s[i + 1..i + 3], 16) {
                out.push(b);
                i += 3;
                continue;
            }
        }
        out.push(bytes[i]);
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// Read file paths from the general pasteboard's `public.file-url` items, if any.
/// This is what Finder puts on the pasteboard when you copy files (alongside a
/// plain-text filename fallback that we must NOT prefer).
fn file_urls_on_pasteboard() -> Option<Vec<String>> {
    let pb = NSPasteboard::generalPasteboard();
    let items = pb.pasteboardItems()?;
    let file_url_type = NSString::from_str("public.file-url");
    let mut paths = Vec::new();
    for item in items.iter() {
        if let Some(s) = item.stringForType(&file_url_type) {
            if let Some(p) = file_url_to_path(&s.to_string()) {
                paths.push(p);
            }
        }
    }
    if paths.is_empty() {
        None
    } else {
        Some(paths)
    }
}

pub struct MacClipboard {
    inner: arboard::Clipboard,
}

impl MacClipboard {
    pub fn new() -> Result<Self, String> {
        Ok(MacClipboard {
            inner: arboard::Clipboard::new().map_err(|e| e.to_string())?,
        })
    }

    fn change_count() -> i64 {
        let pb = NSPasteboard::generalPasteboard();
        pb.changeCount() as i64
    }

    fn is_concealed() -> bool {
        let pb = NSPasteboard::generalPasteboard();
        let Some(types) = pb.types() else {
            return false;
        };
        types.iter().any(|t| {
            let s = t.to_string();
            CONCEALED_TYPES.iter().any(|c| *c == s)
        })
    }
}

impl Clipboard for MacClipboard {
    fn snapshot(&mut self) -> ClipboardSnapshot {
        let change_token = Self::change_count() as u64;
        let concealed = Self::is_concealed();
        // File URLs first: copying files in Finder also exposes a plain-text
        // filename fallback, which we must NOT prefer over the actual files.
        let content = if let Some(files) = file_urls_on_pasteboard() {
            Some(Content::Files(files))
        } else if let Ok(text) = self.inner.get_text() {
            if text.is_empty() {
                None
            } else {
                Some(Content::Text(text))
            }
        } else if let Ok(img) = self.inner.get_image() {
            Some(Content::Image {
                bytes: tagged_rgba(&img),
            })
        } else {
            None
        };
        ClipboardSnapshot {
            content,
            change_token,
            concealed,
        }
    }

    fn set_text(&mut self, text: &str) -> Result<(), String> {
        self.inner
            .set_text(text.to_string())
            .map_err(|e| e.to_string())
    }

    fn set_content(&mut self, content: &Content) -> Result<(), String> {
        match content {
            Content::Text(t) => self.inner.set_text(t.clone()).map_err(|e| e.to_string()),
            Content::Rich { text, .. } => {
                self.inner.set_text(text.clone()).map_err(|e| e.to_string())
            }
            Content::Files(paths) => self
                .inner
                .set_text(paths.join("\n"))
                .map_err(|e| e.to_string()),
            Content::Image { .. } => Err("image set not supported in v1".into()),
        }
    }
}

/// Stable, dimension-tagged raw-RGBA blob so identical images hash equal.
/// (Real PNG re-encoding + thumbnailing happens in the app's image cache.)
fn tagged_rgba(img: &arboard::ImageData) -> Vec<u8> {
    let mut out = Vec::with_capacity(8 + img.bytes.len());
    out.extend_from_slice(&(img.width as u32).to_le_bytes());
    out.extend_from_slice(&(img.height as u32).to_le_bytes());
    out.extend_from_slice(&img.bytes);
    out
}

#[cfg(test)]
mod tests {
    use super::{file_url_to_path, percent_decode};

    #[test]
    fn decodes_finder_file_urls() {
        assert_eq!(
            file_url_to_path("file:///Users/me/a%20b.png"),
            Some("/Users/me/a b.png".to_string())
        );
        assert_eq!(
            file_url_to_path("file:///tmp/x"),
            Some("/tmp/x".to_string())
        );
        // Directory URLs get a trailing slash from Finder.
        assert_eq!(
            file_url_to_path("file:///Users/me/dir/"),
            Some("/Users/me/dir".to_string())
        );
    }

    #[test]
    fn rejects_non_file_urls() {
        assert_eq!(file_url_to_path("https://example.com"), None);
        assert_eq!(file_url_to_path(""), None);
    }

    #[test]
    fn root_url_decodes_to_root_path() {
        assert_eq!(file_url_to_path("file:///"), Some("/".to_string()));
    }

    #[test]
    fn bare_scheme_with_no_path_is_none() {
        assert_eq!(file_url_to_path("file://"), None);
    }

    #[test]
    fn incomplete_percent_escape_is_preserved_literally_without_panicking() {
        // Only 1 char follows '%' (not 2), so the decode loop can't consume a
        // full escape and must fall back to passing '%' through unchanged.
        assert_eq!(percent_decode("/a%2"), "/a%2");
        assert_eq!(file_url_to_path("file:///a%2"), Some("/a%2".to_string()));
    }

    #[test]
    fn invalid_hex_escape_is_passed_through_unchanged() {
        assert_eq!(percent_decode("/a%zz"), "/a%zz");
        assert_eq!(file_url_to_path("file:///a%zz"), Some("/a%zz".to_string()));
    }
}
