[package]
name = "magpie-app"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "magpie"
path = "src/main.rs"

[dependencies]
magpie-core = { path = "../magpie-core" }
magpie-platform = { path = "../magpie-platform" }
slint = "1.8"
tray-icon = "0.24"
global-hotkey = "0.6"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
dirs = "5"
image = "0.25"
regex = "1"

[build-dependencies]
slint-build = "1.8"
