name: ci
on: [push, pull_request]
jobs:
  check:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --workspace
      - run: cargo clippy --workspace --all-targets -- -D warnings
